### PR TITLE
Various improvements for DE locale

### PR DESCRIPTION
**Pull request by svenpanne**

### CODE REVIEW

**Comment by Sharlikran** [comment]
Just a note, one sorta important thing. I do need to make some names for the columns for the XML and then seperate strings for the UI. The reason is that the XML and the Lua code have to match so you can not have the Lua and XML lookinf for Price you you translated it to Preis.

```lua
-- Old string for compatibility
ZO_CreateStringId("MM_OLD_TIP_FORMAT_SINGLE", "M.M. price (%s, %d day): %.2f")
ZO_CreateStringId("MM_OLD_TIP_FORMAT_MULTI", "M.M. price (%s, %d days): %.2f")
ZO_CreateStringId("SK_OLD_PRICETIP_SALES", "<<1[%d sale/%d sales]>>")
ZO_CreateStringId("MM_OLD_PRICETIP_ITEMS", "/<<1[%d item/%d items]>>")

111
The arguments do not need updated or changed. You may have noticed that through.

**Comment by Sharlikran** [comment]
Thanks for all the translations so far

**Comment by svenpanne** [comment]
> [...] I do need to make some names for the columns for the XML and then seperate strings for the UI. The reason is that the XML and the Lua code have to match so you can not have the Lua and XML looking for Price you you translated it to Preis. I have not done that yet, but I need to.

I don't really understand that. What I figured out so far: Some strings are passed to `string.format()`, while others are passed to `zo_strformat`. The format strings for those functions are fundamentally different, but if you see the i18n files only, you have no clue whatsoever which translation should use which kind of format string. Something like a consistent naming scheme to differentiate those strings would be _highly_ appreciated.

Regarding you remark: I don't understand which string will have to match what, i.e. what can be translated and what can't be. If some strings are just really only keys from one data structure to another, they don't belong into the i18n files _and_ those keys should never be presented in the GUI. Could you elaborate a bit?

> The arguments do not need updated or changed. You may have noticed that through.

I didn't touch the `_OLD_` strings IIRC, but OTOH I don't understand why they are there at all. Can they be changed? Can they be removed? If not, why not?

**Comment by Sharlikran** [comment]
> I don't understand which string will have to match what, i.e. what can be translated and what can't be

image

I won't be able to find the entire conversation. Needless to say things are not done properly and it was just a fyi or heads up that at some point in the future I will need to have names that are not translated for the xml and the Lua code for the column names, and then a separate string that you can translate for the UI.

> I didn't touch the _OLD_ strings IIRC, but OTOH I don't understand why they are there at all.

Someone is using MM to get the tip line. Meaning they want this string.

`M.M. Price (608 sales, 90 Days): 2,571`

image

After I changed it then it broke the mod and the Beta testers made the typical comment "Your last update broke the Price Tooltip mod" I can't even play now, just letting you know.

Do the OLD_FORMAT strings are there because I have an alias routine in `MasterMerchant_Alias.lua` for compatibility.

**Pull request closed without merging**
